---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/credentials":
    get:
      summary: list credentials
      tags:
      - Credentials
      responses:
        '200':
          description: successful
    post:
      summary: create credential
      tags:
      - Credentials
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                env:
                  type: string
                utility_id:
                  type: integer
              required:
              - username
              - password
  "/api/v1/credentials/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show credential
      tags:
      - Credentials
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    patch:
      summary: update credential
      tags:
      - Credentials
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                env:
                  type: string
                utility_id:
                  type: integer
    put:
      summary: update credential
      tags:
      - Credentials
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                env:
                  type: string
                utility_id:
                  type: integer
              required:
              - username
              - password
              - env
              - utility_id
    delete:
      summary: delete credential
      tags:
      - Credentials
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
